controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
update_partie:
    path: '/update-partie/{partieId}'
    controller: 'App\Controller\CompteController@updatePartie'

rejoindre_partie:
    path: '/jeu/{id}/{numJoueur}'
    controller: 'App\Controller\CompteController@rejoindrePartie'

